### ISSUE TITLE
Files directory not writable

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdrop-pantheon#10] opened 2016-10-27 19:33 UTC
We changed backdrop to drupal behind the scenes to get the dashboard drush/update/cache-clear working, but now it's looking for files in the wrong place.

The recommended solution is to add a new directory "sites/default" and add a symlink from "files" to "sites/default/files" so that Pantheon's normal "Drupal" symlinking will work with the place where backdrop is looking for it's files.

**Comment by serundeputy** [comment] 2016-10-27 19:37
oh; my.  so does that allow update hooks to fire from dash?

**Comment by jenlampton** [comment] 2016-10-27 19:57
it should!

**Comment by JAyenGreen** [comment] 2016-12-29 23:22
How do you achieve this with regards to workflow? Given there's no ssh access to Pantheon, do you put sites/default/files and Backdrop's 'files' under git control? I hadn't gotten as far as the read-only problem yet...I was still wrapping my brain around whether the workflow was meant to be git -> push -> switch to ftp -> upload config files -> switch back to git

**Comment by jenlampton** [comment] 2016-12-30 20:29
Ideally `files` would never be under Git control. The database is managing the contents of that files directory and having Git try to manage it also would create a huge mess.

For sites I have on pantheon I have tried two solutions, for both symlink `/sites/default/files` to `/files` so that Backdrop's `/files` location matches pantheon's magic file handling. (and you can commit the symlink to Git so it happens across all environments)

Then either 
1)
**Don't verson control your config files**. For me - this misses most of the convenience of using Backdrop + config mgmt, but it works for my smaller sites. Instead, I use the Config Mgmt UI to export from prod, import to dev (or local), make my changes, deploy my code, then import my changed config, again using the config mgmt UI.

or 2)
**Move the config staging directory (only) into version control.** You can put it outside the `/files` directory and add it to Git. The trick here is remembering to manually copy all the files from active into staging (and commit them) before each deploy. 

or (someday) 3)
**Move all config out of the `/files` directory, and into vcs** NOTE: I haven't been able to get this to work yet, since the only writable directory in the files system is the files directory, but I've heard rumors that such a set-up may be possible soon.

**Comment by JAyenGreen** [comment] 2017-01-04 23:33
Thank you, Jen. Option 2 seems the way to go for me. Much appreciated!

**Comment by kreynen** [comment] 2018-08-15 03:54
I ran into this when trying to clone a dev instance into a test instance for the first time.  We've used this repo as the upsteam for several Pantheon instances while testing, but were only using the dev and multidev configurations.  I was a little surprised to run into these errors when creating the test instance since the Pantheon option to Try Backdrop is so prominent on b.org.  I went a slightly different route with https://github.com/CuBoulder/backdrop-pantheon/commit/5e46249a529250b66b0f118a84eb137fd1ea842b.  Pantheon doesn't care where the files directory at the /srv/bindings/xxxx/files are used in code, but this makes the code/files writable as well as backing up and cloning.  

In addition to that change, I added a check for settings.local.php in the /srv/bindings/xxxx/.drush directory since that is also writable.  

```
/**
 * Pantheon specific compatibility.
 *
 * Override the database information to pass the correct Database credentials
 * directly from Pantheon to Backdrop.
 */
if (isset($_SERVER['PRESSFLOW_SETTINGS'])) {
  $_SERVER['BACKDROP_SETTINGS'] = $_SERVER['PRESSFLOW_SETTINGS'];
  if (file_exists('../settings.local.php')) {
    include '../.drush/settings.local.php';
  }
}
```

This allowed me to set the githubapi_client_id and githubapi_client_secret differently for the dev, test and live instances.  

While I was able to get this working, I'm pretty familiar with Pantheon.  The average user is really going to struggle with this.

**Comment by herbdool** [comment] 2018-08-21 03:07
@kreynen your commit seems cleaner since its pointing to the original directory, but is it superior otherwise? Or do either solutions fix the original error?

**Comment by kreynen** [comment] 2018-08-21 18:12
The "original error" isn't as much an error as something Pantheon doesn't support... yet.  I see this as a chicken/egg issue.  Pantheon isn't going to provide full support for Backdrop until there is a documented demand.  The documented demand will never exist until sites can run on the host without issues.  

The real fix needs to happen in the upstream type configuration.  There are certain tweaks Pantheon makes to the symlinks and communication between the dashboard UI and CMS based on whether the type is set to Drupal 7, Drupal 8 or WordPress.

While Pantheon won't prevent users from running anything they can get installed, they won't really support it.  I don't think going from Try Backdrop -> dev on Pantheon in STFP mode -> test on Pantheon with fatal errors is a great initial experience for either Backdrop or Pantheon.  

Based on what I currently know about Backdrop and Pantheon, I think Pantheon is a great host for Backdrop and a great service for Backdrop's target market... but it requires some changes to this upstream.

**Comment by herbdool** [comment] 2018-08-21 19:06
I'm trying to understand the reasons for pointing the symlink of `/files` to `../files` rather than `/sites/default/files`. Just so it's clear why this should be changed in this project.

From what I understand it seems that both symlinks work but the new PR is cleaner?

**Comment by kreynen** [comment] 2018-08-21 20:15
It isn't our workflow exactly, but I found the difference. Pantheon is treating sites created with this upstream differently from a custom upstream that an organizational customer creates from it.

I should have done more testing with the sites using this before making the PR, but basically https://github.com/backdrop-ops/backdrop-pantheon/pull/20 is doing the same thing in the repo that is happening for sites that use this upstream via some other process.

The reason @jenlampton doesn't have this issue because /srv/bindings/xxx/code/files **IS** being converted to a symlink for sites created on default upstream, but not the custom upstreams created from forks of it.  Through some Pantheon magic, code/files being changed from what's actually in https://github.com/backdrop-ops/backdrop-pantheon/tree/master/files into a symlink.  

With our intial test sites, we created dev sites from this upstream and cloned them down to multidev instances.  Everything worked fine.

It wasn't until we started our upstream that we ran into this.  I even asked Pantheon's support whether the upstream should use the D7 or D8 type options.  They never mentioned this as a potential issue... no one on Gitter knew anything about it... and this issue was still open.

I jumped to the conclusion that main repo needed this change, but it's really only the custom upstreams because they aren't being treated the same way.

I don't know what is happening behind the scenes to make this work, but those sites don't have https://github.com/backdrop-ops/backdrop-pantheon/issues/17 either.  

I need to be able to reproduce these changes in our upstream or fix them in this repo for this to be maintainable.  We can't manage an install profile of code on a per-site basis.  In order to get from 1 site to 10 sites, we really need to be able to manage the Backdrop sites the same way we manage the D7 and D8 sites.  

I know many universities use custom Pantheon upstreams including https://open.berkeley.edu/.  This gets really expensive at 1000 sites, but is very cost effective at 100.

**Comment by jenlampton** [comment] 2018-08-21 21:13
I think the Pantheon magic might have been added by @greg1anderson. Maybe he can shed some light?

**Comment by greg-1-anderson** [comment] 2018-08-23 13:49
A custom upstream should follow the instructions to set the [filemount path](https://pantheon.io/docs/pantheon-yml/#filemount-path) in its pantheon.upstream.yml file. When the upstream is created, it should have a `drupal` framework (not `drupal8`).

Under this configuration, the files directory should not be backed up. (n.b. you should add `files` to .gitignore as specified in the above-linked instructions to avoid committing files to the repository.) If you observe that your `files` directory is being backed up, please report it to support.

**Comment by herbdool** [comment] 2018-08-23 18:29
As per @greg-1-anderson recommendations, I've got a [PR](https://github.com/backdrop-ops/backdrop-pantheon/pull/23) that creates pantheon.upstream.yml and adds the filemount.

**Comment by serundeputy** [comment] 2018-09-11 11:40
This is fixed in https://github.com/backdrop-ops/backdrop-pantheon/pull/23

**Closed by serundeputy** 2018-09-11 11:40 UTC
